name: Test (Unit + Integration)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: yarn

      - name: Create Test DB
        run: touch prisma/test.db
      
      - name: Migrate Test DB
        run: npx prisma migrate --experimental up

      - name: Integration Tests
        run: yarn test:db

      - name: Unit Tests
        run: yarn test:unit